baseurl = "http://seedstack.org/"
MetaDataFormat = "yaml"

[params]
  description = "SeedStack, Clean Java development stack"
  author = "The SeedStack authors"
  "ch.qos.logback.version" = "1.1.10"
  "org.seedstack.poms.version" = "3.0.0"
  "org.seedstack.seed.version" = "3.0.3"
  "org.seedstack.business.version" = "3.0.1"
  "org.seedstack.addons.audit.version" = "3.0.0"
  "org.seedstack.addons.datasecurity.version" = "1.0.0"
  "org.seedstack.addons.elasticsearch.version" = "3.0.0"
  "org.seedstack.addons.i18n.version" = "3.0.0"
  "org.seedstack.addons.io.version" = "3.0.0"
  "org.seedstack.addons.javamail.version" = "3.0.0"
  "org.seedstack.addons.jcache.version" = "3.0.0"
  "org.seedstack.addons.jdbc.version" = "3.0.0"
  "org.seedstack.addons.jms.version" = "3.0.0"
  "org.seedstack.addons.jpa.version" = "3.0.0"
  "org.seedstack.addons.metrics.version" = "1.0.0"
  "org.seedstack.addons.mongodb.version" = "2.0.0"
  "org.seedstack.addons.monitoring.version" = "3.0.0"
  "org.seedstack.addons.mqtt.version" = "2.0.0"
  "org.seedstack.addons.neo4j.version" = "2.0.0"
  "org.seedstack.addons.redis.version" = "2.0.0"
  "org.seedstack.addons.scheduling.version" = "3.0.0"
  "org.seedstack.addons.shell.version" = "1.0.0"
  "org.seedstack.addons.solr.version" = "2.0.0"
  "org.seedstack.addons.spring.version" = "3.0.1"
  "org.seedstack.addons.swagger.version" = "2.0.0"
  "org.seedstack.addons.w20.version" = "3.0.0"
  "org.seedstack.addons.ws.version" = "3.0.0"

[blackfriday]
  angledQuotes = true
  plainIdAnchors = true

[taxonomies]
  tag = "tags"
  author = "authors"
  zone = "zones"
  section = "sections"

#####################################
#### Website zones               ####
#####################################

[params.zone.Overview]
  path = "/docs"
  label = "Overview"
  logo = "seed-logo.svg"

[params.zone.Seed]
  path = "/docs/seed"
  label = "Java framework"
  logo = "seed-logo.svg"

[params.zone.Business]
  path = "/docs/business"
  label = "Business framework"
  logo = "business-logo.svg"

[params.zone.GettingStarted]
  path = "/getting-started"
  label = "Getting started"
  logo = "getting-started-logo.svg"

[params.zone.Glossary]
  path = "/glossary"
  label = "Glossary"
  logo = "glossary-logo.svg"

[params.zone.Guides]
  path = "/guides"
  label = "Guides"
  logo = "guides-logo.svg"

[params.zone.Project]
  path = "/project"
  label = "Project"
  logo = "project-logo.svg"

[params.zone.Posts]
  path = "/posts"
  label = "Posts"
  logo = "blog-logo.svg"

[params.zone.Addons]
  path = "/addons"
  label = "Add-ons"
  logo = "addons-logo.svg"

[params.zone.Search]
  path = "/search"
  label = "Search"
  logo = "search-logo.svg"

#####################################
#### Project sections           ####
#####################################

[params.section.ProjectOverview]
  label = "Overview"
  icon = "fa fa-file-text"
  path = ""

[params.section.ProjectCommunity]
  label = "Community"
  icon = "fa fa-community"
  path = "community"

[params.section.ProjectFAQ]
  label = "FAQ"
  icon = "fa fa-comments-o"
  path = "faq"

[params.section.ProjectRoadmap]
  label = "Roadmap"
  icon = "fa fa-road"
  path = "roadmap"

[params.section.ProjectOldVersions]
  label = "Old versions"
  icon = "fa fa-archive"
  path = "old-versions"

#####################################
#### Getting started sections    ####
#####################################

[params.section.GettingStartedQuickStart]
  label = "Quick start"
  icon = "fa fa-rocket"
  path = ""

[params.section.GettingStartedProjectTemplates]
  label = "Project templates"
  icon = "fa fa-cubes"
  path = "project-templates"

[params.section.GettingStartedTutorial]
  label = "Tutorial"
  icon = "fa fa-graduation-cap"
  path = "tutorial"

#####################################
#### Overview sections           ####
#####################################

[params.section.OverviewEssentials]
  label = "Overview"
  icon = "fa fa-certificate"
  path = ""

[params.section.OverviewMavenPlugin]
  label = "Maven plugin"
  icon = "fa fa-cogs"
  path = "maven-plugin"

[params.section.OverviewRuntime]
  label = "Runtime"
  icon = "fa fa-server"
  path = "runtime"

#####################################
#### Business framework sections ####
#####################################

[params.section.BusinessIntroduction]
  label = "Introduction"
  icon = "fa fa-file-text"
  path = ""

[params.section.BusinessManual]
  label = "Business manual"
  icon = "fa fa-book"
  path = "manual"

#####################################
#### Seed framework sections     ####
#####################################

[params.section.SeedEssentials]
  label = "Essentials"
  icon = "fa fa-compass"
  path = ""

[params.section.SeedManual]
  label = "Seed manual"
  icon = "fa fa-book"
  path = "manual"

#####################################
#### Search                      ####
#####################################

[params.section.SearchResults]
  label = "Search results"
  icon = "fa fa-search"
  path = ""

